<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN-5CG134879M" failures="1" tests="1" name="Default test" time="20.775" errors="0" timestamp="2024-04-18T11:08:06 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="19.584">
    <failure type="java.lang.AssertionError" message="expected [Thanks! We value your feedback] but found [Feedback contains no characters]">
      <![CDATA[java.lang.AssertionError: expected [Thanks! We value your feedback] but found [Feedback contains no characters]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinition.WriteReview.form_should_not_be_submitted(WriteReview.java:176)
at âœ½.form should not be submitted(file:///C:/Temp/Review/src/test/resource/Features/Reviews.feature:50)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
