<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LIN-5CG134879M" failures="1" tests="1" name="TestRunner.TestRunner" time="19.584" errors="0" timestamp="2024-04-18T11:08:07 IST" skipped="0">
  <testcase classname="TestRunner.TestRunner" name="runScenario" time="19.584">
    <failure message="expected [Thanks! We value your feedback] but found [Feedback contains no characters]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Thanks! We value your feedback] but found [Feedback contains no characters]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinition.WriteReview.form_should_not_be_submitted(WriteReview.java:176)
at âœ½.form should not be submitted(file:///C:/Temp/Review/src/test/resource/Features/Reviews.feature:50)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestRunner.TestRunner -->
